config/routes.rb
Rails.application.routes.draw do
  resources :reemper_valorations, :except => [:show]
  resources :contac_reempers, :except => [:show]
  resources :consulting_rooms, :except => [:edit]
  get "My/:name/Editar", to: "consulting_rooms#edit", as: "my_roms"
  get "reemper/my/:name/editar(/:token)", to: "reempers#edit", as: "reemper_edit"
  patch "My/:name", to: "consulting_rooms#update", as: "update_room"
  resources :reempers, :except => [:index, :show]
  get "reempers/:name", to: "reempers#show", as: "reemper_registration"
  get "reemper_info/:id", to: "reempers#reemper_info", as: "reemper_info"
  get "remp/:categoria", to: "home#informacion", as: "info"
  resources :subspecialties, :except => [:show]
  resources :specialties, :except => [:show]
  resources :professions, :except => [:show]
  resources :categories, :except => [:show]

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  default_url_options :host => 'reemp.herokuapp.com' 
  devise_scope :admin do

    #get "users/new_user", to: "users/admin#new_user", as: "new_user"
    #get "users/index", to: "users/admin#index", as: "usuarios"
    #get "users/editar_user/:id/", to: "users/admin#editar_user", as: "editar_user"
    #post "update_user", to: "users/admin#update_user", as: "update_user"
    get "new", to: "admins/registrations#new_form", as: "new"
    post "new_admin", to: "admins/registrations#create", as: 'new_admin'
    delete "destroy/:id", to: "admins/registrations#destroy", as: "destroy"
    patch "editar_admin/:id", to: "admins/registrations#editar_admin", as: "editar_admin"
    post "update_admin", to: "admins/registrations#update_a", as: "update_admin"

  end
  
  
  get 'home/index', as: "home"
  get "reemper/home", to: "home#reemper_home", as: "reeper_home"
  root "home#user_contact"
  post "create_contact", to: "contacts#create", as: "create_contact"
  post "reemper_contact", to: "contac_reempers#request_reemper", as: "reemper_contact"

  get "request_remp", to: "reempers#request_remp", as: "request_remp"
  post "update_reemper/:lat/:lng(/:act)", to: "reempers#update_reemper", as: "update_reemper"
  post "update_consul/:lat/:lng(/:act)", to: "consulting_rooms#update_consul", as: "update_consul"

  get "admin/home", to: "home#admin_home", as: "admin_home"
  get "admin/contact", to: "home#admin_contact", as: "admin_contact"
  get "admin/users", to: "home#admin_users", as: "admin_users"
  get "admin/all_admins", to: "home#all_admins", as: "all_admins"
  get "buscador(/:category)(/:specialties)(/:city)", to: "home#buscador", as: "buscador"
  post "browser", to: "home#search", as: "browser"
  delete "contact_delete/:id", to: "contacts#destroy", as: "contact_delete"
  get "admin/all_reempers", to: "home#reemper_registers", as: "reemper_registers"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/parciales/_consultorio.html.erb
<div class="col-md-4 no-padding" style="max-width: 25%;">
    <%= consultorio.first_photo? ? image_tag(consultorio.first_photo_url(), class: "img-thumbnail") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-not")%>
</div>

<div class="col-md-4 no-padding" style="max-width: 25%;">
    <%= consultorio.sub_photo? ? image_tag(consultorio.sub_photo_url(), class: "img-thumbnail") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-not")%>
</div>

<div class="col-md-4 no-padding" style="max-width: 25%;">
	<img src="https://st2.depositphotos.com/1017986/11089/i/950/depositphotos_110891284-stock-photo-group-of-happy-medics-or.jpg" alt="">
</div>

<div class="col-md-4 no-padding" style="max-width: 25%;">
	<img src="https://st2.depositphotos.com/1017986/11089/i/950/depositphotos_110891284-stock-photo-group-of-happy-medics-or.jpg" alt="">
</div>

app/views/parciales/_info_privacity.html.erb
<p>
	El presente Política de Privacidad establece los términos en que Reemp usa y protege la información que es proporcionada por sus usuarios al momento de utilizar su sitio web. Esta compañía está comprometida con la seguridad de los datos de sus usuarios. Cuando le pedimos llenar los campos de información personal con la cual usted pueda ser identificado, lo hacemos asegurando que sólo se empleará de acuerdo con los términos de este documento. Sin embargo esta Política de Privacidad puede cambiar con el tiempo o ser actualizada por lo que le recomendamos y enfatizamos revisar continuamente esta página para asegurarse que está de acuerdo con dichos cambios.
</p>

<strong>Información que es recogida</strong>

<p>
	Nuestro sitio web podrá recoger información personal por ejemplo: Nombre,  información de contacto como  su dirección de correo electrónica, información demográfica, profesión y especialidad. Así mismo cuando sea necesario podrá ser requerida información específica para procesar algún pedido o realizar una entrega o facturación.
</p>

<strong>Uso de la información recogida</strong>

<p>
	Nuestro sitio web emplea la información con el fin de proporcionar el mejor servicio posible, particularmente para mantener un registro de usuarios, de pedidos en caso que aplique, y mejorar nuestros productos y servicios.  Es posible que sean enviados correos electrónicos periódicamente a través de nuestro sitio con ofertas especiales, nuevos productos y otra información publicitaria que consideremos relevante para usted o que pueda brindarle algún beneficio, estos correos electrónicos serán enviados a la dirección que usted proporcione y podrán ser cancelados en cualquier momento.
</p>

<p>
	Reemp está altamente comprometido para cumplir con el compromiso de mantener su información segura. Usamos los sistemas más avanzados y los actualizamos constantemente para asegurarnos que no exista ningún acceso no autorizado.
</p>

<strong>Cookies</strong>


<p>
	Una cookie se refiere a un fichero que es enviado con la finalidad de solicitar permiso para almacenarse en su ordenador, al aceptar dicho fichero se crea y la cookie sirve entonces para tener información respecto al tráfico web, y también facilita las futuras visitas a una web recurrente. Otra función que tienen las cookies es que con ellas las web pueden reconocerte individualmente y por tanto brindarte el mejor servicio personalizado de su web.
</p>

<p>
	Nuestro sitio web emplea las cookies para poder identificar las páginas que son visitadas y su frecuencia. Esta información es empleada únicamente para análisis estadístico y después la información se elimina de forma permanente. Usted puede eliminar las cookies en cualquier momento desde su ordenador. Sin embargo las cookies ayudan a proporcionar un mejor servicio de los sitios web, estás no dan acceso a información de su ordenador ni de usted, a menos de que usted así lo quiera y la proporcione directamente, <a href="www.reemp.co">Reemp</a> Usted puede aceptar o negar el uso de cookies, sin embargo la mayoría de navegadores aceptan cookies automáticamente pues sirve para tener un mejor servicio web. También usted puede cambiar la configuración de su ordenador para declinar las cookies. Si se declinan es posible que no pueda utilizar algunos de nuestros servicios.
</p>

<strong>Enlaces a Terceros</strong>

<p>
	Este sitio web pudiera contener en laces a otros sitios que pudieran ser de su interés. Una vez que usted de clic en estos enlaces y abandone nuestra página, ya no tenemos control sobre al sitio al que es redirigido y por lo tanto no somos responsables de los términos o privacidad ni de la protección de sus datos en esos otros sitios terceros. Dichos sitios están sujetos a sus propias políticas de privacidad por lo cual es recomendable que los consulte para confirmar que usted está de acuerdo con estas.
</p>

<strong>Control de su información personal</strong>

<p>
	En cualquier momento usted puede restringir la recopilación o el uso de la información personal que es proporcionada a nuestro sitio web.  Cada vez que se le solicite rellenar un formulario, como el de alta de usuario, puede marcar o desmarcar la opción de recibir información por correo electrónico.  
</p>

<p>
	En caso de que haya marcado la opción de recibir nuestro boletín o publicidad usted puede cancelarla en cualquier momento.
	Esta compañía no venderá, cederá ni distribuirá la información personal que es recopilada sin su consentimiento, salvo que sea requerido por un juez con un orden judicial.
	Reemp Se reserva el derecho de cambiar los términos de la presente Política de Privacidad en cualquier momento.
</p>

app/views/parciales/_menu_show.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="" style="padding-left: 60px;">
    <img src="https://mybc1.s3.amazonaws.com/uploads/rseguimiento/evidencia/401/logo_reemp_blanco.png" class="logo-img">
  </a>

  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      </li>
    </ul>

    <span class="navbar-text" style="padding-right: 57px;">
      <% if user_signed_in? %>
        <div class="row">
          <%= link_to "Reemper", reeper_home_path , class: "btn-logins" %>

          <div class="dropdown">
            <button class="btn-user dropdown-toggle" type="button" id="dropdownMenu2" data-toggle="dropdown" >
             <i class="fas fa-user-circle icon-user" ></i> <%= current_user.names %>
            </button>
            <div class="dropdown-menu  dropdown-menu-right" aria-labelledby="dropdownMenu2" id="manu-show">
              <%= link_to "Configuracion de tu cuenta", edit_user_registration_path, class: "dropdown-item", target: "_blank" %>
              <button class="dropdown-item" type="button">Historial</button>
              <% if remmper_have %>
                <button class="dropdown-item" type="button">Ya Eres Reemper</button>
              <% else %>
                <%= link_to "Conviertete en Reemper", new_reemper_path, class: "dropdown-item" %>
              <% end -%>
              <%= link_to "Cerrar Sección", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

            </div>
          </div>
        </div>

      <% else %>
        <button class="btn-logins" data-toggle="modal" data-target="#exampleModalCenter">Ingresar</button>
      <% end -%>
    </span>
  </div>
</nav>

<script src="https://maps.googleapis.com/maps/api/js?sensor=false&libraries=places&language=en&key=AIzaSyBCTHCpTg9kTvg7uBcO0wYvpA7_Tw8Lkxg"></script>
<style type="text/css" media="screen">

  .btn-logins{
    background: inherit;
    border-radius: 55px;
    border: 2px solid #22D3B1;
    color: #ffff !important;
    padding: 10px 50px 10px 50px;
    margin-right: 20px;
  }

  .icon-user{
    font-size: 20px;
    margin-right: 4px;
  }

  .btn-user{
    background: inherit;
    border-radius: 55px;
    color: #ffff !important;
    padding: 10px;
    margin-right: 20px;
    border: initial;
  }

  .btn-reemper{
    margin-right: 3px;
  }

  .logo-img{
    width: 200px;
  }

  .navbar{
    margin-bottom: 0px;
    padding-bottom: 0px;
    height: 84px;
  }

  .submit1{
    background: #210554;
    color: #fff;
    border: initial;
    padding: 8px;
    border-radius: 25px;
    position: absolute;
    top: -41px;
    right: -38px;
  }

  #manu-show{
    left: -196px;
    width: 225%;
    text-align: right !important;
    top: 127%;
    background: #ececef;
  }

</style>


<script type="text/javascript">

jQuery(document).ready(function($) {

  $('.dropdown').on('show.bs.dropdown', function () {
      $("#manu-show").toggle("size");
  })

  $('.dropdown').on('hide.bs.dropdown', function () {
      $("#manu-show").toggle("size");
  })


});
</script>

app/views/parciales/_reemper_info.html.erb
<div class="container">
    <div class="row row-style">
		<div class="col-md-3 no-padding">
		    <img class="img-xs rounded-circle" src="https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg" id="reemper-img" />
		</div> 

		<div class="col-md-5 no-padding-right">
		    <h6 id="name" style="margin-bottom: 5px;"></h6>   
		    <p style="margin-bottom: 0px;" id="cirugia"></p>
		    <p style="margin-bottom: 0px;"><i class="fas fa-star good" ></i><i class="fas fa-star "></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i></p>
		    <p style="margin-bottom: 0px;" class="ubica">a 1,2k de tu ubicacion</p>
		</div> 

		<div class="col-md-4 no-padding-right">
		    <h6><i class="fab fa-instagram icon-inst"></i> <small class="ubica"> @estiven </small></h6>
			<button class="btn-services">Sitio Web <i class="fas fa-angle-right"></i> </button>
		</div>

		<div class="col-md-12 no-padding espacios">

		 <div class="row row-style" style="margin: 10px 0px 22px 0px; ">
			<div class="col-md-12 no-padding-left">
			<% if user_signed_in?  %>
	          <% if @reemper.user.id == current_user.id  %>

	          <% else %>
	            <%= link_to new_contac_reemper_path(:reemper => @reemper.id), remote: true, class: "btn-services", style: "margin-right: 10px" do %>
	            		Contacto
	            <% end -%>
	          <% end -%>

	          <% else %>

	            <button class="btn-services" data-toggle="modal" data-target="#exampleModalCenter">Contacto</button>

	        <% end -%>
			 	<%= link_to "Enviar Pregunta", new_contac_reemper_path(:reemper => @reemper.id), remote: 
			 	            true, class: "btn btn-primary", style: "display:none" %>
			 	            <button class="btn-services">Servicios y Precios</button>
			 </div>

			
		 </div>

		</div> 

		

		<div class="col-md-12 conten-img no-padding ">
		    <div class="row row-style" id="my-consulto"></div>
		</div>

	
		<div class="col-md-12 show-info" style="padding: 10px;margin-top: 22px;"> 
		  <p id="biograpy" style="margin-bottom: 0px;" ></p>
		  <label  style="float: right;" id="btn-show">Mas Sobre Mi</label>
		</div>

		<div class="col-md-12 text-center">
			<button type="" class="btn-cita" id="cita-btn">Citar</button>
		</div>

		<ul class="nav nav-pills col-md-12 no-padding" id="pills-tab" role="tablist">
			<li class="nav-item">
		    	<a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Reseñas</a>
		    </li>

		    <li class="nav-item" disabled>
			    <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false" >(<%= @valoration.count %> opiniones)</a>
		    </li>
		</ul>

		<div class="tab-content col-md-12 no-padding" id="pills-tabContent">
		    <div class="panel tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab" style="    padding: 0px;">     
		    <div id="valoration"></div>
		    </div>
		    <div class="panel tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">...</div>
		</div>


	</div>
</div>

app/views/parciales/_sesion.html.erb
<div class="modal fade " id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content border">
      <div class="modal-body">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="tab" role="tabpanel">
                    <!-- Nav tabs -->
                  <ul class="nav nav-tabs" role="tablist">
                    <li role="presentation" class=""><a class="" href="#Section4" aria-controls="home" role="tab" data-toggle="tab" id="btn-tab">Iniciar Sesion</a></li>
                    <li role="presentation"><a href="#Section5" aria-controls="profile" role="tab" data-toggle="tab" id="btn-tab1">Crear Cuenta</a></li>
                  </ul>
                    <!-- Tab panes -->
                  <div class="tab-content tabs">
                  <div role="tabpanel" class="tab-pane animated bounceInLeft in active" id="Section4">
                          <%= render "devise/sessions/new" %>
                  </div>
                  <div role="tabpanel" class="tab-pane animated bounceInRight" id="Section5">
                          <%= render "devise/registrations/new_user"%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<style type="text/css" media="screen">

.btn1{
      border-radius: 17px;
      border: none;
      padding: 5px;
      width: 52%;
      cursor: pointer;
      background: linear-gradient(to right, #ff8c00, #ff0080); 
      color: #fff;
}

.form1{
    border-radius: 21px;
    margin-bottom: 5px;
    background: #c5c5c512 !important;
}

a:hover,a:focus{
    outline: none;
    text-decoration: none;
}

.tab .nav-tabs{
    border: none;
    margin-bottom: 10px;
}

#btn-tab{
    display: block;
    padding: 10px;
    margin: 0 10px 0 0;
    background: #fcfcfc;
    font-size: 13px;
    letter-spacing: 1px;
    color: #fff;
    width: 177%;
    left: -8px;
    background: #01BAFE;
    border: 1px solid #eee;
    border-radius: 27px;
    overflow: hidden;
    position: relative;
    z-index: 1;
    text-align: center;
}

#btn-tab1:hover{
  border: 1px solid #01BAFE !important;
  background: #fff !important;
  color: #01BAFE !important;
}

#btn-tab:hover{
  border: 1px solid #01BAFE !important;
  background: #fff !important;
  color: #01BAFE !important;
}



#btn-tab1{
    display: block;
    padding: 10px;
    margin: 0 10px 0 0;
    background: #fcfcfc;
    font-size: 13px;
    letter-spacing: 1px;
    color: #fff;
    width: 162%;
    left: 95px;
    background: #01BAFE;
    border: 1px solid #eee;
    border-radius: 27px;
    overflow: hidden;
    position: relative;
    z-index: 1;
    text-align: center;
}


.tab .nav-tabs li a:after{
    background: #000;
    transition: all 0.4s ease-in 0.3s;
}

.tab .nav-tabs li.active a:before,
.tab .nav-tabs li.active a:after{
    opacity: 1;
    transform: scale(4);
}

.tab .tab-content{
    margin-top: 0;
    font-size: 15px;
    color: #fff;
    line-height: 30px;
    letter-spacing: 1px;
    position: relative;
}

  li > .active{
    border: 1px solid #01BAFE !important;
    background: #fff !important;
    color: #01BAFE !important;
  }

.tab .tab-content h3{
    font-size: 24px;
    margin-top: 0;
}

@media only screen and (max-width: 767px){
  .tab .nav-tabs li a{ padding: 7px 15px; }
}
@media only screen and (max-width: 479px){
.tab .nav-tabs li{
  width: 100%;
  text-align: center;
  margin-bottom: 15px;
}
.tab .nav-tabs li a:before,
.tab .nav-tabs li a:after{
    width: 100%;
  }
}

@media (max-width: 576px) {

    #btn-tab{
      width: 100% !important;
      left: -1px !important;
    }

    #btn-tab1{
      width: 100% !important;
      left: -1px !important;
  }  
}

.modal-backdrop{
  background-color: #00000040 !important;
}

  .label{
    color: gray;
  }

</style>

app/views/parciales/_sucess_message.html.erb
<div class="modal animated zoomIn" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content border">
      <div class="modal-body">
        <h2 class="h4" align="center">¡Sus datos han sido enviados </h2>
          <h2 align="center" class="h4">Exitosamente</h2>
          <br>
        <p align="center" class="p">Te Informaremos sobre nuestros avances..</p>
      </div>
    </div>
  </div>
</div>

app/views/parciales/_user.html.erb
<div class="card" style="margin-top: 10px; box-shadow: 0 1px 10px 0 #6e77801c;">
  <div class="card-body no-padding-card">
    <div class="row" style="margin-left: 0px; margin-right: 0px;">

      <div class="col-md-2">
        <%= valoracion.user.avatar? ? image_tag(valoracion.user.avatar_url(), class: "img img-rounded img-fluid ") : image_tag("https://image.ibb.co/jw55Ex/def_face.jpg", class: "img img-rounded img-fluid ")%>
      </div>

      <div class="col-md-10">
        <p>
          <a class="float-left" href="https://maniruzzaman-akash.blogspot.com/p/contact.html"><strong><%= valoracion.user.names %></strong></a>
          <span class="float-right"><%= get_valoration(valoracion.valoration).html_safe %></span>
        </p>

        <br>

        <div class="clearfix"></div>
        <i>"<%= valoracion.description %>"</i>
      </div>
    </div>
  </div>
</div>

app/views/parciales/_user_info.html.erb
<div class="row row-user-info animated fadeIn">
  <i class="fas fa-arrow-left" id="back"></i>
  <div class="col-md-12">
    <strong class="title-cate">Mas Sobre Mi</strong>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries</p>
  </div>

  <div class="col-md-12">
    <strong class="title-cate">Estudios</strong>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries</p>
  </div>

  <div class="col-md-12">
    <strong class="title-cate">Experiencia</strong>
    <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries</p>
  </div>

</div>

  <div class="col-md-12 text-center" style="margin-top: 15px;">
    <button type="" class="btn-cita">Citar</button>
  </div>



<script type="text/javascript">
  $("#back").click(function(event) {
    $("#info-reemp").removeClass('none').addClass('show animated fadeIn');
    $(".remplace").addClass('none');

  if($('#info-reemp').css('display') != 'show')
      console.log($('#info-reemp'));
    { 

    }
  });
</script>