config/routes.rb
Rails.application.routes.draw do
  resources :reemper_valorations, :except => [:show]
  resources :contac_reempers, :except => [:show]
  resources :consulting_rooms, :except => [:edit]
  get "My/:name/Editar", to: "consulting_rooms#edit", as: "my_roms"
  get "reemper/my/:name/editar(/:token)", to: "reempers#edit", as: "reemper_edit"
  patch "My/:name", to: "consulting_rooms#update", as: "update_room"
  resources :reempers, :except => [:index, :show]
  get "reempers/:name", to: "reempers#show", as: "reemper_registration"
  get "reemper_info/:id", to: "reempers#reemper_info", as: "reemper_info"
  get "remp/:categoria", to: "home#informacion", as: "info"
  resources :subspecialties, :except => [:show]
  resources :specialties, :except => [:show]
  resources :professions, :except => [:show]
  resources :categories, :except => [:show]

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  default_url_options :host => 'reemp.herokuapp.com' 
  devise_scope :admin do

    #get "users/new_user", to: "users/admin#new_user", as: "new_user"
    #get "users/index", to: "users/admin#index", as: "usuarios"
    #get "users/editar_user/:id/", to: "users/admin#editar_user", as: "editar_user"
    #post "update_user", to: "users/admin#update_user", as: "update_user"
    get "new", to: "admins/registrations#new_form", as: "new"
    post "new_admin", to: "admins/registrations#create", as: 'new_admin'
    delete "destroy/:id", to: "admins/registrations#destroy", as: "destroy"
    patch "editar_admin/:id", to: "admins/registrations#editar_admin", as: "editar_admin"
    post "update_admin", to: "admins/registrations#update_a", as: "update_admin"

  end
  
  
  get 'home/index', as: "home"
  get "reemper/home", to: "home#reemper_home", as: "reeper_home"
  root "home#user_contact"
  post "create_contact", to: "contacts#create", as: "create_contact"
  post "reemper_contact", to: "contac_reempers#request_reemper", as: "reemper_contact"

  get "request_remp", to: "reempers#request_remp", as: "request_remp"
  post "update_reemper/:lat/:lng(/:act)", to: "reempers#update_reemper", as: "update_reemper"
  post "update_consul/:lat/:lng(/:act)", to: "consulting_rooms#update_consul", as: "update_consul"

  get "admin/home", to: "home#admin_home", as: "admin_home"
  get "admin/contact", to: "home#admin_contact", as: "admin_contact"
  get "admin/users", to: "home#admin_users", as: "admin_users"
  get "admin/all_admins", to: "home#all_admins", as: "all_admins"
  get "buscador(/:category)(/:specialties)(/:city)", to: "home#buscador", as: "buscador"
  post "browser", to: "home#search", as: "browser"
  delete "contact_delete/:id", to: "contacts#destroy", as: "contact_delete"
  get "admin/all_reempers", to: "home#reemper_registers", as: "reemper_registers"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!, :only => [:reemper_home]
  before_action :authenticate_admin!, :only => [:admin_home, :admin_contact, :admin_users, :all_admins] 
	layout "application", :only => [:index, :user_contact]
  layout "user", :only => [:reemper_home]

  def index
    categoria = Category.where(name: "Salud")
    @specialties = Specialty.where(category_id: categoria).all

    catemas = Category.where(name: "Mascotas")
    @specmas = Specialty.where(category_id: catemas).all

    catecons = Category.where(name: "Construccion")
    @specate = Specialty.where(category_id: catecons).all

    catelegal = Category.where(name: "Legal")
    @specilegal = Specialty.where(category_id: catelegal).all

  end

  def search

    @categoria = params[:category_id]
    @especialidad = params[:specialties]
    @costru = params[:search2]
    @ciudad = params[:city]


    categoria = Category.where(name: "Salud")
    @category = Specialty.where(category_id: categoria).first

    catemas = Category.where(name: "Mascotas")
    especialidad = Specialty.where(category_id: catemas).first

    catecons = Category.where(name: "Construccion")
    @specate = Specialty.where(category_id: catecons).first

    #if @category.present?
     # redirect_to buscador_path(@category.name, @ciudad)

    ## redirect_to buscador_path(@especialidad.name, @ciudad)
    #end

    redirect_to buscador_path(@categoria, @especialidad, @ciudad)
  end

  def inicio
  	
  end

  def informacion

    if params[:categoria] == "Salud"

        categoria = Category.where(name: "Salud")
        @specialties = Specialty.where(category_id: categoria).all

        render json: @specialties

      elsif params[:categoria] == "Mascotas"

        catemas = Category.where(name: "Mascotas")
        @specmas = Specialty.where(category_id: catemas).all

        render json: @specmas

      elsif params[:categoria] == "Construccion"

        catecons = Category.where(name: "Construccion")
        @specate = Specialty.where(category_id: catecons).all

        render json: @specate

      elsif params[:categoria] == "Legal"  
        catelegal = Category.where(name: "Legal")
        @specilegal = Specialty.where(category_id: catelegal).all
        
        render json: @specilegal

    end

  end

  def buscador
   @specate = params[:specialties]
   @categorias = params[:category]
   @ciudad = params[:city]

    categoria = Category.where(name: "Salud")
    @specialties = Specialty.where(category_id: categoria).all
  end

  def user_contact
    
  end

  def reemper_home
    usuario = User.where(id: current_user.id)
    reemper = Reemper.where(user_id: usuario)
    @reemper_valoration = ReemperValoration.where(reemper_id: reemper)
  end

  def reemper_registers
    @reempers = Reemper.all
    render :layout => "admin" 
  end

  def admin_home
    render :layout => "admin" 
  end

  def admin_contact
    @contacts = Contact.all.paginate(:page => params[:page], :per_page => 6)
    render :layout => "admin" 
  end

  def admin_users
    @users = User.all.paginate(:page => params[:page], :per_page => 6)
    render :layout => "admin" 
  end

  def all_admins
    @admins = Admin.all.paginate(:page => params[:page], :per_page => 6)
    render :layout => "admin" 
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/admin_contact.html.erb
<% if @contacts.any? %>
<legend>Contacto</legend>
<table class="table js-scrollable">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Email</th>
      <th>Ciudad</th>
      <th>Categoria</th>
      <th>Especialidad</th>
      <th>Profesion</th>
      <th>Instagram</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name if contact %></td>
        <td><%= contact.email if contact %></td>
        <td><%= contact.city if contact %></td>
        <td><%= contact.category.name if contact.category %></td>
        <td><%= contact.specialty_name if contact %></td>
        <td><%= contact.profession_name if contact %></td>
        <td><%= contact.instagram if contact %></td>
          <td class="text-center">
            <%= link_to contact_delete_path(contact.id), method: :delete, data: {
                confirm: '¿Estas Seguro?',
                'confirm-button-text': 'Borrar',
                'cancel-button-text': 'Cancelar',
                'confirm-button-color': '#CC0000',
                 text: 'Recuerda que el registro se borrara permanentemente',
                'image-url': ''}, class: "btn btn-danger" do %>
              <span class="glyphicon glyphicon-trash"></span> 
            <% end -%>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<% else %>
  <h1 align="center">todavia no nos han contactado!</h1>
<% end -%>

  <div class = "col-md-12 paginate text-center title-table1">
    <nav class="pagination-outer" aria-label="Page navigation">
      <%= will_paginate @contacts, renderer: BootstrapPagination::Rails, previous_label: "&laquo;", next_label: "&raquo;", inner_window: 1, outer_window: 0 %>
    </nav>
  </div>

<style type="text/css" media="screen">

  .btn1:hover{
    color: #fff;
  }
</style>

<script type="text/javascript">
  <% if flash[:delete].present? %>
    toastr["error"]("<%= flash[:delete] %> con <b>Exito!</b>");
  <% end -%>
</script>

app/views/home/admin_home.html.erb
<h1>hola admin</h1>

<script type="text/javascript">
  <% if notice.present? %>
    toastr["info"]("<b><%= notice %></b>");
  <% end -%>
</script>

app/views/home/admin_users.html.erb
<% if @users.any? %>
<legend>Usuarios Registrados</legend>
<table class="table">
  <thead>
    <tr>
      <th>Avatar</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Nombre de Usuario</th>
      <th>Email</th>
      <th>Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
      	<td>
      	<%= user.avatar? ? image_tag(user.avatar_url(), class: "img-xs rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-xs rounded-circle")%>
      	</td>
        <td><%= user.names %></td>
        <td><%= user.last_names %></td>
        <td><%= user.user_name %></td>
        <td><%= user.email %></td>
          <td class="text-center">
            <%= link_to contact_delete_path(user.id), method: :delete, data: {
                confirm: '¿Estas Seguro?',
                'confirm-button-text': 'Borrar',
                'cancel-button-text': 'Cancelar',
                'confirm-button-color': '#CC0000',
                 text: 'Recuerda que el registro se borrara permanentemente',
                'image-url': ''}, class: "btn btn-danger" do %>
              <span class="glyphicon glyphicon-trash"></span> 
            <% end -%>
          </td>
        </tr>
    <% end %>
  </tbody>
</table>


  <div class = "col-md-12 paginate text-center title-table1">
      <%= will_paginate @users, renderer: BootstrapPagination::Rails, previous_label: "&laquo;", next_label: "&raquo;", inner_window: 1, outer_window: 0 %>
  </div>
<% else %>
  <h1 align="center">Todavia No hay Usuarios!</h1>
<% end -%>


<script type="text/javascript">
  <% if flash[:delete].present? %>
    toastr["error"]("<%= flash[:delete] %> con <b>Exito!</b>");
  <% end -%>
</script>

app/views/home/all_admins.html.erb
<% if @admins.any? %>
<legend>Administradores</legend>
<table class="table">
  <thead>
    <tr>
      <th class="text-left">Avatar</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th class="text-center">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
      	<td class="text-left">
      	<%= admin.avatar? ? image_tag(admin.avatar_url(), class: "img-xs rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-xs rounded-circle")%>
      	</td>
        <td><%= admin.name %></td>
        <td><%= admin.last_name %></td>
        <td><%= admin.email %></td>
        <td class="text-center">
        <% if current_admin.email == admin.email %>
        
        <% else %>
            <%= link_to destroy_path(admin.id), method: :delete, title: "Emilinar Cuenta", data: {
                confirm: '¿Estas Seguro?',
                'confirm-button-text': 'Borrar',
                'cancel-button-text': 'Cancelar',
                'confirm-button-color': '#CC0000',
                 text: 'Recuerda que el registro se borrara permanentemente',
                'image-url': ''}, class: "btn btn-danger" do %>
              <span class="glyphicon glyphicon-trash"></span> 
            <% end -%>
        <% end -%>

            <%= link_to editar_admin_path(admin.id), remote: true, method: :patch, class: "btn btn-primary", title: "Editar" do %>
              <i class="fas fa-user-edit"></i>
            <% end -%>

          </td>
        </tr>
    <% end %>
  </tbody>
</table>

<div class="sk-cube-grid" id="cube">
  <div class="sk-cube sk-cube1"></div>
  <div class="sk-cube sk-cube2"></div>
  <div class="sk-cube sk-cube3"></div>
  <div class="sk-cube sk-cube4"></div>
  <div class="sk-cube sk-cube5"></div>
  <div class="sk-cube sk-cube6"></div>
  <div class="sk-cube sk-cube7"></div>
  <div class="sk-cube sk-cube8"></div>
  <div class="sk-cube sk-cube9"></div>
</div>


<div class="modal-footer">
  <%= link_to 'Nuevo Administrador', new_path, remote: true, class: "btn btn-success"%>
</div>

  <div class = "col-md-12 paginate text-center title-table1">
      <%= will_paginate @admins, renderer: BootstrapPagination::Rails, previous_label: "&laquo;", next_label: "&raquo;", inner_window: 1, outer_window: 0 %>
  </div>
<% else %>
  <h1 align="center">todavia no nos han contactado!</h1>
<% end -%>



<script type="text/javascript">
  <% if flash[:delete].present? %>
    toastr["error"]("<%= flash[:delete] %> con <b>Exito!</b>");
  <% end -%>
</script>



<style type="text/css" media="screen">
.sk-cube-grid {
  width: 40px;
  height: 40px;
  margin: 100px auto;
    position: absolute;
    top: 107px;
    left: 400px;
    display: none;
}

.sk-cube-grid .sk-cube {
  width: 33%;
  height: 33%;
  background: linear-gradient(120deg, #00e4d0, #5983e8);
  float: left;
  -webkit-animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out;
          animation: sk-cubeGridScaleDelay 1.3s infinite ease-in-out; 
}

.sk-cube-grid .sk-cube1 {
  -webkit-animation-delay: 0.2s;
          animation-delay: 0.2s; }
.sk-cube-grid .sk-cube2 {
  -webkit-animation-delay: 0.3s;
          animation-delay: 0.3s; }
.sk-cube-grid .sk-cube3 {
  -webkit-animation-delay: 0.4s;
          animation-delay: 0.4s; }
.sk-cube-grid .sk-cube4 {
  -webkit-animation-delay: 0.1s;
          animation-delay: 0.1s; }
.sk-cube-grid .sk-cube5 {
  -webkit-animation-delay: 0.2s;
          animation-delay: 0.2s; }
.sk-cube-grid .sk-cube6 {
  -webkit-animation-delay: 0.3s;
          animation-delay: 0.3s; }
.sk-cube-grid .sk-cube7 {
  -webkit-animation-delay: 0s;
          animation-delay: 0s; }
.sk-cube-grid .sk-cube8 {
  -webkit-animation-delay: 0.1s;
          animation-delay: 0.1s; }
.sk-cube-grid .sk-cube9 {
  -webkit-animation-delay: 0.2s;
          animation-delay: 0.2s; }

@-webkit-keyframes sk-cubeGridScaleDelay {
  0%, 70%, 100% {
    -webkit-transform: scale3D(1, 1, 1);
            transform: scale3D(1, 1, 1);
  } 35% {
    -webkit-transform: scale3D(0, 0, 1);
            transform: scale3D(0, 0, 1); 
  }
}

@keyframes sk-cubeGridScaleDelay {
  0%, 70%, 100% {
    -webkit-transform: scale3D(1, 1, 1);
            transform: scale3D(1, 1, 1);
  } 35% {
    -webkit-transform: scale3D(0, 0, 1);
            transform: scale3D(0, 0, 1);
  } 
}
</style>

app/views/home/reemper_home.html.erb
<% if @reemper_valoration.any? %>
	<legend>Tus Valoraciones <%= current_user.names %> </legend>
	
	<div class="row">
		<% @reemper_valoration.each do |valoracion| %>
			<div class="col-md-6">
				<div class="card" style="box-shadow: 0 1px 10px 0 #6e77801c;">
					<div class="card-body no-padding-card">
					    <div class="row">

					      <div class="col-md-3 no-padding">
					        <%= valoracion.user.avatar? ? image_tag(valoracion.user.avatar_url(), class: "img-fluid img-avatar") : image_tag("https://image.ibb.co/jw55Ex/def_face.jpg", class: "img img-rounded img-fluid ")%>
					      </div>

					      <div class="col-md-9">
					        <p>
					          <a class="float-left" href=""><strong><%= valoracion.user.names? ? valoracion.user.names : "Usuario Reemp" %></strong></a>
					          <span class="float-right"><%= get_valoration(valoracion.valoration).html_safe %></span>
					        </p>

					        <br>

					        <div class="clearfix"></div>
					        <i>"<%= valoracion.description %>"</i>
					      </div>

					    </div>
					</div>
				</div>
			</div>
		<% end -%>
	</div>

<% else %>
	<h1>hola <%= current_user.names? ? current_user.names : "Usuario Reemp" %></h1>
<% end -%>


<script type="text/javascript">
	<% if notice.present? %>
		    toastr["success"]("<%= notice %>");
	<% end -%>
</script>

<style type="text/css" media="screen">

.img-avatar{
	border-radius: 50%;
    height: 107px;
    margin-top: 2px;
}

</style>

app/views/home/reemper_registers.html.erb
<% if @reempers.any? %>
<legend>Reempers Registrados</legend>
<table class="table">
  <thead>
    <tr>
      <th class="width text-center">Avatar</th>
      <th class="width text-center">Nombre</th>
      <th class="width text-center">Apellido</th>
      <th class="width-email text-center">Email</th>
      <th class="text-center width">Telefono</th>
      <th class="width text-center">Acciones</th>
    </tr>
  </thead>

    <tbody>
      <% @reempers.each do |reemper| %>
        <tr>
        	<td class="text-center">
        	<%= reemper.user.avatar? ? image_tag(reemper.user.avatar_url(), class: "img-xs rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-xs rounded-circle")%>
        	</td>
          <td class="text-center"><%= reemper.user.names if reemper.user %></td>
          <td class="text-center"><%= reemper.user.last_names if reemper.user %></td>
          <td class="text-left"><%= reemper.user.email %></td>
          <td class="text-center"><%= reemper.user.phone if reemper.user %></td>

          <td>

          <label class="label-show" data-toggle="modal" data-target="#modal-show<%= reemper.id %>">Informacion</label>
          <div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true" id="modal-show<%= reemper.id %>">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="container-fluid">
                  <div class="row">

                  <div class="col-md-4">
                    <legend>PERSONAL</legend><br>

                    <strong>Tipo de Documento</strong>
                    <p><%= reemper.document_type %></p>  

                    <strong>Numero de Documento</strong>
                    <p><%= reemper.document_numer %></p>   

                    <strong>Ciudad</strong>
                    <p><%= reemper.city %></p>   

                  </div>

                  <div class="col-md-4">
                    <legend>INFORMACION ACADEMICA</legend><br>

                    <strong>Nivel Academico</strong>
                    <p><%= reemper.academy_level %></p>  

                    <strong>Univesidad</strong>
                    <p><%= reemper.university %></p>   

                    <strong>Profession</strong>
                    <p><%= reemper.profession %></p>                 
                  </div>

                  <div class="col-md-4">
                    <legend>INFORMACION ADICIONAL</legend><br>

                    <strong>Categoria</strong>
                    <p><%= reemper.category.name %></p>  

                    <strong>Especialidad</strong>
                    <p><%= reemper.specialty.name %></p>   

                    <strong>Idiomas</strong>
                    <p><%= reemper.language %></p>  

                  </div>

                  <div class="col-md-12" style=" white-space: normal; ">
                      <legend>BIOGRAFIA</legend>
                        <%== reemper.biography %>
                  </div>

                  <% consultorio =  ConsultingRoom.where(user_id: reemper.user.id) %>

                  <% if consultorio.any? %>

                    <div class="col-md-12" style="margin-top: 20px;">
                      <div class="container">
                        <div class="row">
                        
                          <legend>Informacion del Consultorio</legend>

                            <% consultorio.each do |consultorio|%>

                                <div class="col-md-8 no-padding-left">
                                  <legend>Imagenes</legend>

                                  <div class="col-md-6 no-padding-left img">
                                    <%= consultorio.first_photo? ? image_tag(consultorio.first_photo_url(), class: "") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "")%>
                                  </div>

                                  <div class="col-md-6 no-padding-right img1">
                                    <%= consultorio.sub_photo? ? image_tag(consultorio.sub_photo_url(), class: "") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "")%>
                                  </div>
                                  
                                </div>

                                <div class="col-md-4 no-padding-right">
                                  <legend>Ubicacion</legend>
                                  <div id="map"></div>

                                <script type="text/javascript">
                                  function initMap() {
                                    var myLatLng = {lat: <%= consultorio.lat %>, lng: <%= consultorio.lng %>};

                                    // Create a map object and specify the DOM element
                                    // for display.
                                    var map = new google.maps.Map(document.getElementById('map'), {
                                      center: myLatLng,
                                      zoom: 5
                                    });

                                    // Create a marker and set its position.
                                    var marker = new google.maps.Marker({
                                      map: map,
                                      position: myLatLng,
                                      title: 'Hello World!'
                                    });
                                  }
                                  </script>

                                  
                                </div>

                            <% end -%>

                        </div>

                        <% end -%>
                      </div>  
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <%= link_to destroy_path(reemper.id), method: :delete, title: "Emilinar Cuenta", data: {
                  confirm: '¿Estas Seguro?',
                  'confirm-button-text': 'Borrar',
                  'cancel-button-text': 'Cancelar',
                  'confirm-button-color': '#CC0000',
                   text: 'Recuerda que el registro se borrara permanentemente',
                  'image-url': ''}, class: "btn btn-danger" do %>
            <span class="glyphicon glyphicon-trash"></span> 
          <% end -%>

          <%= link_to "ver", reemper_registration_path(:name => reemper.user.names), target: '_blank'%>

          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end -%>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCTHCpTg9kTvg7uBcO0wYvpA7_Tw8Lkxg&callback=initMap"async defer></script>
<style type="text/css" media="screen">

  .img img{
    width: 100% !important;
    height: 160px !important;
    border-radius: inherit !important;
  }

  .img1 img{
    width: 100% !important;
    height: 160px !important;
    border-radius: inherit !important;
  }

  .width{
    width: 10%;
  }

  .width-email{
    width: 22%;
  }

  .email{
    max-width: 0px;
    overflow-x: overlay;
  }

  .label-show{
    cursor: pointer;
    background-color: #47cbd4;
    padding: 3px;
    border-radius: 3px;
    color: #fff;
  }

  .modal-content{
    padding: 10px;
    border-radius: 0px;
    background-clip: initial;
    box-shadow: 0 3px 9px #47cbd4 !important;
  }

  #map{
    height: 161px;
  }

  #map img{
    border-radius: inherit !important;
  }


</style>