config/routes.rb
Rails.application.routes.draw do
  resources :reemper_valorations, :except => [:show]
  resources :contac_reempers, :except => [:show]
  resources :consulting_rooms, :except => [:edit]
  get "My/:name/Editar", to: "consulting_rooms#edit", as: "my_roms"
  get "reemper/my/:name/editar(/:token)", to: "reempers#edit", as: "reemper_edit"
  patch "My/:name", to: "consulting_rooms#update", as: "update_room"
  resources :reempers, :except => [:index, :show]
  get "reempers/:name", to: "reempers#show", as: "reemper_registration"
  get "reemper_info/:id", to: "reempers#reemper_info", as: "reemper_info"
  get "remp/:categoria", to: "home#informacion", as: "info"
  resources :subspecialties, :except => [:show]
  resources :specialties, :except => [:show]
  resources :professions, :except => [:show]
  resources :categories, :except => [:show]

  devise_for :users, :controllers => { :registrations => "users/registrations" }
  devise_for :admins, :controllers => { :registrations => "admins/registrations" }
  default_url_options :host => 'reemp.herokuapp.com' 
  devise_scope :admin do

    #get "users/new_user", to: "users/admin#new_user", as: "new_user"
    #get "users/index", to: "users/admin#index", as: "usuarios"
    #get "users/editar_user/:id/", to: "users/admin#editar_user", as: "editar_user"
    #post "update_user", to: "users/admin#update_user", as: "update_user"
    get "new", to: "admins/registrations#new_form", as: "new"
    post "new_admin", to: "admins/registrations#create", as: 'new_admin'
    delete "destroy/:id", to: "admins/registrations#destroy", as: "destroy"
    patch "editar_admin/:id", to: "admins/registrations#editar_admin", as: "editar_admin"
    post "update_admin", to: "admins/registrations#update_a", as: "update_admin"

  end
  
  
  get 'home/index', as: "home"
  get "reemper/home", to: "home#reemper_home", as: "reeper_home"
  root "home#user_contact"
  post "create_contact", to: "contacts#create", as: "create_contact"
  post "reemper_contact", to: "contac_reempers#request_reemper", as: "reemper_contact"

  get "request_remp", to: "reempers#request_remp", as: "request_remp"
  post "update_reemper/:lat/:lng(/:act)", to: "reempers#update_reemper", as: "update_reemper"
  post "update_consul/:lat/:lng(/:act)", to: "consulting_rooms#update_consul", as: "update_consul"

  get "admin/home", to: "home#admin_home", as: "admin_home"
  get "admin/contact", to: "home#admin_contact", as: "admin_contact"
  get "admin/users", to: "home#admin_users", as: "admin_users"
  get "admin/all_admins", to: "home#all_admins", as: "all_admins"
  get "buscador(/:category)(/:specialties)(/:city)", to: "home#buscador", as: "buscador"
  post "browser", to: "home#search", as: "browser"
  delete "contact_delete/:id", to: "contacts#destroy", as: "contact_delete"
  get "admin/all_reempers", to: "home#reemper_registers", as: "reemper_registers"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Administracion Reemp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <%= favicon_link_tag "https://mybc1.s3.amazonaws.com/uploads/rseguimiento/evidencia/375/2.png"%>

<link rel="stylesheet" href="https://unpkg.com/scroll-hint@latest/css/scroll-hint.css">
<script src="https://unpkg.com/scroll-hint@latest/js/scroll-hint.min.js"></script>


    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>
  
  <nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
        <a class="navbar-brand brand-logo" href="/admin/home">
          <img src="https://mybc1.s3.amazonaws.com/uploads/rseguimiento/evidencia/374/1.png" alt="logo" />
        </a>
        <a class="navbar-brand brand-logo-mini" href="index.html">
          <img src="https://mybc1.s3.amazonaws.com/uploads/rseguimiento/evidencia/375/2.png" alt="logo" />
        </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">

        <ul class="navbar-nav navbar-nav-left header-links d-none d-md-flex">
          <% if controller_name == "specialties"%>
            <li class="nav-item">
              <%= link_to 'Nueva Especialidad', new_specialty_path, remote: true, class: "nav-link"%>
            </li>
            <% elsif controller_name == "categories"%>
            <li class="nav-item">
              <%= link_to 'Nueva Categoria', new_category_path, remote: true, class: "nav-link"%>
            </li>
            <% elsif controller_name == "subspecialties"%>
            <li class="nav-item">
              <%= link_to 'Nueva Subspecialidad', new_subspecialty_path, remote: true, class: "nav-link"%>
            </li>
          <% end -%>

        </ul>

        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown">
          <li class="nav-item dropdown d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <span class="profile-text d-none">Hola, <%= current_admin.name? ? current_admin.name : "Usuario Reemp" %>!</span>
               <%= current_admin.avatar? ? image_tag(current_admin.avatar_url(), class: "img-xs rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-xs rounded-circle")%>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a class="dropdown-item p-0">

                <div class="d-flex border-bottom">

                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                      <i class="fas fa-user"></i>
                  </div>

                  <div class="py-3 px-4 d-flex align-items-center justify-content-center border-left border-right">
                      <i class="fas fa-users-cog"></i>
                  </div>

                  <div class="py-3 px-4 d-flex align-items-center justify-content-center">
                      <i class="fas fa-user-edit"></i>
                  </div>

                </div>

              </a>

              <%= link_to "Editar Cuenta",  edit_admin_registration_path, class: "dropdown-item" %>

              <% if admin_signed_in?%>
                  <%= link_to "salir", destroy_admin_session_path, method: :delete, class: "dropdown-item" %>
              <% else %>
                  <%= link_to "ingresar", new_admin_session_path, class: "dropdown-item" %>
              <% end -%>
              
            </div>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </nav>
    <!-- partial -->
    <div class="container-fluid page-body-wrapper">
      <!-- partial:partials/_sidebar.html -->
      <nav class="sidebar sidebar-offcanvas" id="sidebar">
        <ul class="nav">
          <li class="nav-item nav-profile">
            <div class="nav-link">
              <div class="user-wrapper">
                <div class="profile-image">
                  <%= current_admin.avatar? ? image_tag(current_admin.avatar_url(), class: "img-xs rounded-circle",id: "user-avatar1") : image_tag("https://dnuba.s3.amazonaws.com/uploads/bank_image/achivo/44/user.jpeg", class: "img-xs rounded-circle")%>
                </div>
                <div class="text-wrapper">
                  <p class="profile-name"><%= current_admin.name? ? current_admin.name : "Usuario Reemp" %></p>
                  <div>
                    <small class="designation text-muted">Administracion</small>
                    <span class="status-indicator online"></span>
                  </div>
                </div>
              </div>

          <% admin_menu %>

          <li class="nav-item <%= @admin[0]%>">
            <%= link_to admin_home_path, class: "nav-link" do %>
                <i class="menu-icon fas fa-home"></i> Home
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[1]%>">
            <%= link_to admin_users_path, class: "nav-link" do %>
                <i class="menu-icon fas fa-user"></i> Usuarios
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[2]%>">
            <%= link_to reemper_registers_path, class: "nav-link" do %>
                <i class="menu-icon fas fa-tachometer-alt"></i> Reempers
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[3]%>">
            <%= link_to admin_contact_path, class: "nav-link" do %>
                <i class="menu-icon fas fa-users"></i> Contacto
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[4]%>">
            <%= link_to all_admins_path, class: "nav-link" do %>
                <i class="menu-icon fas fa-user-tie"></i> Administradores
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[5]%>">
            <%= link_to edit_admin_registration_path, class: "nav-link" do %>
                <i class="menu-icon fas fa-user-edit"></i> Mi Cuenta
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[6]%>">
            <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link" do %>
                <i class="menu-icon fas fa-sign-out-alt"></i> Salir
            <% end -%>
          </li>

          <li class="nav-item <%= @admin[7]%>">
            <a class="nav-link" data-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">
              <i class="menu-icon fas fa-plus-square"></i>
                <span class="menu-title">Creacion</span>
              <i class="menu-arrow"></i>
            </a>
            <div class="collapse" id="ui-basic">
              <ul class="nav flex-column sub-menu">

                <li class="nav-item">
                  <%= link_to categories_path, class: "nav-link" do %>
                      <i class="icon2 fas fa-arrow-right"> </i> Categorias
                  <% end -%>
                </li>

                <li class="nav-item">
                  <%= link_to specialties_path, class: "nav-link" do %>
                      <i class="icon2 fas fa-arrow-right"> </i> Especiadades
                  <% end -%>
                </li>

                <li class="nav-item">
                  <%= link_to subspecialties_path, class: "nav-link" do %>
                      <i class="icon2 fas fa-arrow-right"> </i> Subespecialidades
                  <% end -%>
                </li>

              </ul>
            </div>
          </li>

        </ul>
      </nav>

  <body class="body">

    <div class="main-panel">
      <div class="content-wrapper">
        <div class="row">
          <% if controller_name != "registrations"%>
          <div class="card col-md-12">
            <div class="card-body" style="padding: 10px 10px">
              <%= yield %>
            </div>
          </div>
          <% else  %>
            <%= yield %>
          <% end -%>
        </div>
      </div>
    </div>

  </body>
</html>


<style type="text/css" media="screen">

  .py-3{
    padding: 11px !important;
  }

  .py-3 > .fas{
    color: #5bc0de;
  }

  #new_remper:

  .icon{
    margin-top: 4px;
    font-size: 19px;
    cursor: pointer;
  }

  .icon2{
    margin-right: 6px;
  }

   @media only screen and (min-width: 1600px) {

    /* Large screen, non-retina */
    body{
      zoom: 151% !important;
    }
  }

  .scroll-hint-icon-white {
    background-color: #fff;
    box-shadow: 0 0px 8px rgba(4, 129, 177, 1);
  }

  .sidebar .nav .nav-item .nav-link .badge{
    margin-left: 0px;
    padding: 5px;
  }

    /* width */
  ::-webkit-scrollbar {
    width: 10px;
  }

  /* Track */
  ::-webkit-scrollbar-track {
    box-shadow: inset 0 0 5px grey; 
  }
   
  /* Handle */
  ::-webkit-scrollbar-thumb {
    background-color:  #6DD5FA; 
  }

  /* Handle on hover */
  ::-webkit-scrollbar-thumb:hover {
    background: #0481b169; 
  }

    @media (max-width: 576px) {

      .navbar-menu-wrapper{
        padding: 0px;
      }

      .navbar-nav .nav-item.dropdown .navbar-dropdown {
          right: -12px !important;
      }

      .navbar.default-layout .navbar-menu-wrapper .navbar-nav .nav-item{

        right: -27px !important;
      }

      .navbar-toggler{
        margin-left: 10px;
      }

      .navbar.default-layout .navbar-brand-wrapper .brand-logo-mini img {
          width: calc(101px - 48px);
          max-width: 100%;
          height: 42px;
          margin: auto;
      }


    }

    .modal-backdrop{
          background-color: #00000059 !important;
    }

    /*table asdasd*/
    @media (min-width: 768px) and (max-width: 1024px) {
      
    }


    @media only screen and (max-width: 1000px) {

    }

</style>

<script type="text/javascript">


(function($) {
  'use strict';
  $(function() {
    $('[data-toggle="offcanvas"]').on("click", function() {
      $('.sidebar-offcanvas').toggleClass('active')
    });
  });
})(jQuery);

jQuery(document).ready(function($) {
  new ScrollHint('.js-scrollable', {
    scrollHintIconAppendClass: 'scroll-hint-icon-white', // white-icon will appear
    applyToParents: true,
    i18n: {
      scrollable: 'Ver Mas'
    }
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reemp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.3.1/dist/jquery.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_react' %>
    <%= favicon_link_tag "https://mybc1.s3.amazonaws.com/uploads/rseguimiento/evidencia/375/2.png"%>
    
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  </head>

  <body>
    <%= yield %>
  </body>
</html>


<style type="text/css" media="screen">
  
  body{
    font-family: "Poppins", sans-serif;
  }

    @media only screen and (min-width: 1600px) {

    /* Large screen, non-retina */
    body{
      zoom: 151% !important;
    }
  }

</style>